### ISSUE TITLE
Create token map & re-order token lists

### ISSUE THREAD

**Issue by verenablaschke** [ismla-japanese-helper/japanese-helper#11]
- Currently a stub in the token class
- Should merge 2 (or more??) tokens with the same form
- We should think about whether we should only merge tokens if they also have the same POS tag, so we can take advantage of the tokenizer's POS tags.
  - This requires us to create a mapping from kuromoji POS tags to Wiktionary POS tags.

**Comment by verenablaschke** [comment]
For the POS tag mapping:
- Kuromoji uses some hierarchy for the POS tags associated with each token ([their Token class](https://github.com/atilika/kuromoji/blob/master/kuromoji-ipadic/src/main/java/com/atilika/kuromoji/ipadic/Token.java), [sample output](https://github.com/atilika/kuromoji/blob/1fad6cc5e27e7e512ea59fd6bf453897fa8e9415/kuromoji-ipadic/src/test/resources/jawikisentences-ipadic-features.txt)).
- [Here's ](https://ja.osdn.net/projects/ipadic/docs/ipadic-2.7.0-manual-en.pdf/en/1/ipadic-2.7.0-manual-en.pdf.pdf) a manual for IPAdic that includes a section on POS tagging. I'm not sure how closely kuromoji's output tagset matches this one.

**Comment by verenablaschke** [comment]
We should probably not merge the tokens completely, but rather save them as a list/set that we can re-order for each individual case, based on the kuromoji output (cf. #3). Then, we would pick a subset of the "merged" token, based on 
1. the POS tag
2. the pronunciation (NB that kuromoji returns both a _reading_ and a _pronunciation_, both in katakana.)

**Comment by x-ji** [comment]
Makes sense. Maybe I should do it in `LookupServiceImpl` after all, i.e. when I try to load the `dictoinary-full` file for the Wiktionary tokens? I'll try and see how it goes.

**Comment by verenablaschke** [comment]
Well, we're going to have a map from word forms to Token objects anyway, right?
What if we
- make it a ```Map<String, List<Token>>``` instead where the list contains only one entry if the dictionary only contains one entry for that token, or several entries if we'd have to "merge" the entries.
- (maybe already create this map during the preprocessing step and persist it in a file by serializing it. Then, we only need to de-serialize that file on the server side, which might be quicker than reading in the dictionary file and creating the hashmap.)
- write a method that, given a kuromoji token, returns the applicable sub-list of tokens and/or re-orders the list appropriately

?

**Comment by x-ji** [comment]
Yeah, I was just looking at Guava Multimap https://google.github.io/guava/releases/snapshot/api/docs/com/google/common/collect/Multimap.html for it and was trying to include it in the code. Serialization should be a good idea.
