### ISSUE TITLE
Add a row in the output to show base form + inflection paradigm in addition to the inflected form.

### ISSUE THREAD

**Issue by x-ji** [ismla-japanese-helper/japanese-helper#15]

**Comment by verenablaschke** [comment]
as of 36aeb15, you can get the base token from an InflectedToken via ```getLemmaToken()```

**Comment by x-ji** [comment]
We should also add a row in the output to show the base form in addition to the actual inflected form.

**Comment by x-ji** [comment]
We also need a map from a inflectable base verb to all its inflection forms. This way we can show a full inflection table for any inflected verb.

**Comment by x-ji** [comment]
Added a row to show inflection paradigm e3210a5c224dd0e2df1a735b33a5190b9ef9c34c

**Comment by x-ji** [comment]
I realized that even though I could create a Multimap of a base form's all inflections, it would actually not be easy to transfer this information back to the client following the current framework, where we're using `ArrayList<Token>` to transmit the results. Therefore for now we might just only show the base form instead, as stated in the project proposal.

**Comment by x-ji** [comment]
e77397317add3f5d68be16599335d0b289be2483
