### ISSUE TITLE
if there is more than one token match, show the alternative matches as well

### ISSUE THREAD

**Issue by verenablaschke** [ismla-japanese-helper/japanese-helper#20]
We now sort the list of tokens and just present the token that presents the best match. It would be great if we could also present the alternatives, similarly to how we present the additional translations.

**Comment by x-ji** [comment]
Thanks for the sorting implementation! I can see if I can make another popup to show whole tokens.

**Comment by x-ji** [comment]
It will actually be quite non-trivial to have additional UI popups showing full information of the alternative tokens. Jisho redirects to a full new page if you want to look up a particular token.

 One way to approach it could be to add a section to the glosses popup, where the gloss entries from those alternative tokens are appended. That should be easier to approach.

**Comment by x-ji** [comment]
I made an implementation but somehow the serialization doesn't work. I'll change it to using concrete types and try again.

**Comment by x-ji** [comment]
Now I tried to use `List<ArrayList<Token>>`, and the error is 

`java.lang.ClassCastException: com.google.common.collect.AbstractMapBasedMultimap$RandomAccessWrappedList cannot be cast to java.util.ArrayList`

so apparently the `get` method called on `ListMultimap` returns you a datatype that is not actual normal Java list... Why were we able to serialize it without the outer layer of `List` then? Let me see how to get around this.

**Comment by x-ji** [comment]
Fixed it by manually constructing an `ArrayList` in the `sortTokens` function!

**Comment by x-ji** [comment]
4f3571a07a0709b6936dffda8b846044d0121411
7a79d60e8f4fe3baefa48dc3ce8a707bb1b53877
e4a563cc67e30d668c1c9c7e8e46624a34071eb7
9d4e94f105144b09c2f48988ad38aa10d6b1ea46

Currently the alternative tokens are simply added to the glosses popup (the POS tag is also shown). More complex layout might be used if we have time.
