### ISSUE TITLE
figure out why the program doesn't switch to the results view for input "行って"

### ISSUE THREAD

**Issue by verenablaschke** [ismla-japanese-helper/japanese-helper#29]

**Comment by x-ji** [comment]
Added some debug statements and apparently there is some problem with the `t.getTranslations().get(0)` on `て`...

**Comment by x-ji** [comment]
Seems that the offending entry is `て	て	PRT	1) ### 2) ? 3) ?` in the dictionary dump, which resulted in the `translations` object in this `Token` not being initialized correctly?

**Comment by x-ji** [comment]
Fixed in e456373a7e836bf92fae306e20be9ee0a0c08b80
