### ISSUE TITLE
Analyze the correspondence between Kuromoji tags and Wiktionary tags. Implement the lookup process.

### ISSUE THREAD

**Issue by x-ji** [ismla-japanese-helper/japanese-helper#3]

**Comment by x-ji** [comment]
## IPADIC information
https://hayashibe.jp/tr/mecab/dictionary/ipadic

品詞 / 品詞細分類1
- 名詞
- 動詞
- 形容詞
- 副詞
- 接続詞
- 感動詞
- 助詞
- 助動詞
- 連体詞
- 接頭詞
- 記号: This is just the punctuation marks.
- フィラー: Filler?
- その他: 間投


## Wiktionary Information
https://en.wiktionary.org/wiki/Wiktionary:About_Japanese

They claim their methods to conform to the methods in modern kokugo texts.

- Noun 名詞
- Verbs 動詞
- Adjectives 形容詞
- Adjectival nouns (形容動詞)
  This is classified as a sub-category of Noun, 名詞 - 形容動詞語幹, under the IPADIC scheme
- Adverbs (副詞)
- Conjunctions (接続詞)
- Interjections (感動詞)
- Particles (助詞)
- Auxiliaries (助動詞)
- Adnominals (連体詞)
- Counter words (助数詞)
  This is classified as a sub-sub category of noun, as 名詞 - 接尾 - 助数詞, under the IPADIC scheme.
- Prefixes (接頭辞)
- Suffixes (接尾辞)
  Seems to be classified under three different places, as subcategories of noun, verb and adj respectively.

**Comment by verenablaschke** [comment]
- Kuromoji uses some hierarchy for the POS tags associated with each token ([their Token class](https://github.com/atilika/kuromoji/blob/master/kuromoji-ipadic/src/main/java/com/atilika/kuromoji/ipadic/Token.java), [sample output](https://github.com/atilika/kuromoji/blob/1fad6cc5e27e7e512ea59fd6bf453897fa8e9415/kuromoji-ipadic/src/test/resources/jawikisentences-ipadic-features.txt)).
- [Here's ](https://ja.osdn.net/projects/ipadic/docs/ipadic-2.7.0-manual-en.pdf/en/1/ipadic-2.7.0-manual-en.pdf.pdf) a manual for IPAdic that includes a section on POS tagging. I'm not sure how closely kuromoji's output tagset matches this one.

**Comment by verenablaschke** [comment]
From the Wiktionary dump, I additionally get:
- subsets of N:
  - named entities: NE
  - numerals: NUM
  - pronouns: PRN

**Comment by verenablaschke** [comment]
I'm not sure if we should include this in this issue or create a new one, but we will have to merge some of the kuromoji tokens; at least those for inflected verbs/adjectives. 
Example:
- input: この動物は日本語で何と言いますか。
- kuromoji output: この　動物　は　日本語　で　何　と　**言い　ます**　か。
- what we expect: この　動物　は　日本語　で　何　と　**言います**　か。
(One additional problem with this is that the Wiktionary inflection templates are a bit inconsistent about which forms they include--for instance, ja-go-su, the template for 言う includes 話します/FORMAL and 話さない/NEGATIVE but _not_ 話しません/FORMAL-NEGATIVE.)

**Comment by x-ji** [comment]
Now there is a first implementation. Merging of inflected verbs is still not implemented yet.

**Comment by verenablaschke** [comment]
We should probably also add a ```convertPOSTag``` method for Wiktionary tokens, where we map all the adjectives to a ```A``` and all the verb tags to ```V``` (we might also need to merge the noun-related tags). That way, we can establish a better link between Kuromoji tags and Wiktionary tags while still being able to display the additional information that comes with the Wiktionary tags (inflection paradigm, transitivity).
