### ISSUE TITLE
Create a popup to show full inflection patterns.

### ISSUE THREAD

**Issue by x-ji** [ismla-japanese-helper/japanese-helper#31]
We can add a map in each base token that contains all the inflected tokens from this base token.

**Comment by x-ji** [comment]
However, what we're transmitting to the client for now is still the inflected token... Unless we transmit the base token instead/together and also remember the original inflection/inflected token, this will still not work. Also, storing all the inflected tokens in a base token will increase the size of a token and processing time considerably.

**Comment by verenablaschke** [comment]
5fa7d45 saves lemma tokens for which inflections are generated as ```InflectableToken```s. [LookupServiceImpl.java#L106](https://github.com/ismla-japanese-helper/japanese-helper/blob/5fa7d45800c4b398e71cb9bdbb9fe5dcf30bba03/src/main/java/de/ws1718/ismla/JapaneseHelper/server/LookupServiceImpl.java#L106) shows how to get the necessary information for displaying inflection tables

**Comment by x-ji** [comment]
Thanks for the work! Now the inflection list popup is finally implemented at 1553245f4ecfa44f303fda9536e77a1796826277

**Comment by verenablaschke** [comment]
Thanks, this is great! In 25f7e69, I made sure that the entries in the inflection table also appear in a non-random, more reasonable order.
