### ISSUE TITLE
lock input widget or re-use it for new input

### ISSUE THREAD

**Issue by verenablaschke** [ismla-japanese-helper/japanese-helper#32]
Right now, when we present the results, we still have the SentenceInputWidget at the top of the page (which is great!). However, it looks like it is possible to enter the next text snippet in the input area and submit it for analysis, when clicking the button actually resets the widget. It would be good if we either
 - lock the text input area

or
- use the ```Submit``` button instead of the ```Clear``` button.

**Comment by x-ji** [comment]
Good point. I tried to directly resubmit but there was some problems in cleaning off the already displayed table. I might try to lock it if resubmitting doesn't work.

**Comment by x-ji** [comment]
476fdd92caa64b048be0533201dce04458ec4814
