### ISSUE TITLE
"proper" rows in the result table

### ISSUE THREAD

**Issue by verenablaschke** [ismla-japanese-helper/japanese-helper#36]
i.e. each row should start at the same height for all cells (that are next to each other)

Does Bootstrap allow this or do we need to change the way the table is constructed?

**Comment by x-ji** [comment]
At least I'm glad that the CSS grid and Flexbox knowledge proved to be handy at this instance.

**Comment by x-ji** [comment]
Apparently the original code was just simply not "GWT" enough so I changed the code structure and added a `WordContainerWidget` in 521514bd13b35f990ac67b0f932a201158b8c02e. Now the code organization is much better :) Though I'd still say it takes quite an insane amount of time to write something that would have been easy in plain HTML + CSS + JS...
