### ISSUE TITLE
ignore whitespace tokens

### ISSUE THREAD

**Issue by verenablaschke** [ismla-japanese-helper/japanese-helper#40]
Currently, whitespace (incl. line breaks) is also parsed as tokens and displayed in the results table as such:
```
*
[punctuation mark]
punctuation
*
*
```
It's absolutely uninformative and takes up quite a lot of space. We should trim whitespace from the input more carefully and/or skip"empty" tokens.

**Comment by verenablaschke** [comment]
I don't necessarily agree we should remove all punctuation marks--personally, I find that including them helps me find the tokens that I'm interested in more quickly, since they sort of guide the eye.

**Comment by x-ji** [comment]
Sure. Maybe we can also offer this as an option. By "empty tokens" you mean tokens that don't contain anything, unlike normal punctuation?

**Comment by verenablaschke** [comment]
Yes! Ones that represent some kind of whitespace and that are displayed like the example in the original post.

**Comment by x-ji** [comment]
Is this also needed on the console version and the tokenize file version? Then a similar Regex based solution might work.
