### ISSUE TITLE
Unify indentation standard of the project

### ISSUE THREAD

**Issue by x-ji** [ismla-japanese-helper/japanese-helper#45]
It seems that some files are indented with tabs while some others with spaces. I'm not sure if the maven archetype already created the files with tabs from the beginning. @verenablaschke does your editor use tabs by default? If so I should just change my editor to do the same and unify the indentation standard for the whole project. Otherwise there can be confusions when committing files since the indentation of many lines will be changed at the same time.

**Comment by verenablaschke** [comment]
Yes, my Eclipse preferences are set to using tab-based indentation for Java.

**Comment by x-ji** [comment]
New files are being created with tabs as default. Formatting existing code might be useful some time in the future.
