### ISSUE TITLE
Deal with weird formatting on some of the templates

### ISSUE THREAD

**Issue by x-ji** [ismla-japanese-helper/japanese-helper#5]

**Comment by verenablaschke** [comment]
- entries with the POS tags A[na], A[i] contain spaces
- the templates ja-go-ru and ja-go-nu contain some (apparently redundant) extra information we need to ignore, e.g. ```-->|terminal={{{terminal|る}}}<!--``` should just be ```-->|terminal=る<!--```

(We could also include the extra information on the usage of imperative forms in the templates ja-suru and ja-ichi. This is of low priority though, and could also be moved into a new issue thread.)
