### ISSUE TITLE
Handle/Display alternative forms better, e.g. two imperative forms for spoken and written are currently only labeled as imp1 and imp2

### ISSUE THREAD

**Issue by x-ji** [ismla-japanese-helper/japanese-helper#6]

**Comment by verenablaschke** [comment]
If we implement this, we should also do this for the additional inflection templates added in #9.

**Comment by verenablaschke** [comment]
The linked commit deals with the cases where the template contains footnotes about the usage of certain inflection forms. 

We could additional add a note to those inflection forms where では is contracted to じゃ, although that should be more obvious to the user.

**Comment by verenablaschke** [comment]
fd00ddf handles the important cases
