### ISSUE TITLE
Deal with the special cases of inflections. Might need some manual processing

### ISSUE THREAD

**Issue by x-ji** [ismla-japanese-helper/japanese-helper#9]

**Comment by verenablaschke** [comment]
no templates for:
- A[tari]
- VI1[verbconj] (-> ある、する、くれる)
- A[?]
- VI1[kuru]

when looking up [suru] verbs, strip away the suffixed する

**Comment by verenablaschke** [comment]
tari と+ある＝たる・と＋あり＝たり

[https://ja.wikipedia.org/wiki/形容動詞#タルト型活用](https://ja.wikipedia.org/wiki/形容動詞#タルト型活用)
[https://ja.wikipedia.org/wiki/形容動詞#タリ活用](https://ja.wikipedia.org/wiki/形容動詞#タリ活用)

**Comment by verenablaschke** [comment]
**A[?]**

161 entries are tagged as A[?]. I looked up the source pages for the first five entries:
- [様](https://en.wiktionary.org/wiki/%E6%A7%98#Adjective): inflected according to *ja-na*
- [真](https://en.wiktionary.org/wiki/%E7%9C%9F#Adjective): no inflection.
- [貴](https://en.wiktionary.org/wiki/%E8%B2%B4#Adjective): no inflection.
- [さとい](https://en.wiktionary.org/wiki/%E3%81%95%E3%81%A8%E3%81%84): no inflection, contains a link to its kanji version which also isn't inflected.
- [あし](https://en.wiktionary.org/wiki/%E3%81%82%E3%81%97#Adjective): no inflection, contains a link to a non-existing page for its kanji version.

Plus another entry further down the list:
- [忌まわしい](https://en.wiktionary.org/wiki/%E5%BF%8C%E3%81%BE%E3%82%8F%E3%81%97%E3%81%84): inflected according to *ja-i*.

Are most* of these ～な adjectives? (On Wiktionary, ～い adjectives are listed *with* their suffix, い, but ～な adjectives are listed *without* final な.) I don't know a lot about Japanese adjectives though and have no intuition about them, so this is just a guess.
[* Those not ending in い, at least.]

We could either ignore these entries, or heuristically decide what type of adjective they are.

**Comment by verenablaschke** [comment]
This is pretty much completed! I'll leave it open for now in case:
- I find more information about tari/taru adjectives
- the next update includes an A[nari] category
  - Even if it does not, we could consider manually tagging the few nari/naru adjectives as such and add a ja-nari inflection either way.
